# Generated by Django 6.0.1 on 2026-04-04 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='products',
            new_name='category',
        ),
    ]
